load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "CPPLib",
    srcs = ["cpplib.cpp", "util.cpp", "day1solver.cpp"],
    hdrs = ["cpplib.h", "util.h", "day1solver.h"],
    visibility = ["//visibility:public"]
    )
