load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "CPPLib",
    srcs = [
        "cpplib.cpp",
        "util.cpp",
        "day1solver.cpp",
        "day2solver.cpp",
        "day3solver.cpp",
        "day4solver.cpp"
        ],
    hdrs = [
        "cpplib.h",
        "util.h",
        "day1solver.h",
        "day2solver.h",
        "day3solver.h",
        "day4solver.h"
        ],
    visibility = ["//visibility:public"]
    )
