cc_test(
    name = "tests",
    srcs = glob(["**/*.cpp"]),
    deps = [
        "//src/lib:CPPLib",
        "@googletest//:gtest_main"
        ],
    data = ["testData/simpleIntegers.txt", "day1/testdata.txt"]
    )
