cc_test(
    name = "tests",
    srcs = glob(["**/*.cpp"]),
    deps = [
        "//src/lib:CPPLib",
        "@googletest//:gtest_main"
        ],
    data = [
        "testData/simpleIntegers.txt",
        "day1/testdata.txt",
        "day1/testdata2.txt",
        "day2/testdata.txt",
        "day3/testdata.txt",
        "day4/testdata.txt",
        "day5/testdata.txt"
        ]
    )
